### ISSUE TITLE
6-2_PCA.ipynb 코드 수정

### ISSUE THREAD

**Issue by dlgur1994** [wikibook/ml-definitive-guide#1]
import pandas as pd

df = pd.read_excel('credit_card.xls', sheet_name='Data')
print(df.shape)
df.head(3)

이부분에서
df를 책에 나온 코드로 해야 header가 바뀌면서 다음 단계 수행이 가능합니다.
df = pd.read_excel('credit_card.xls', header=1, sheet_name='Data').iloc[0:, 1:]

**Comment by wikibook** [comment]
안녕하세요. 위키북스 담당자입니다.
먼저 불편을 드려 죄송합니다.
말씀해 주신 내용을 저자분께 전달했고, 해당 코드 내용을 수정했습니다. 
또한 홈페이지 정오표에도 반영했으니 참고 부탁드립니다.

https://wikibook.co.kr/ml-definitive-guide/

감사합니다.
