### ISSUE TITLE
7-1_KMeans.ipynb 코드 수정

### ISSUE THREAD

**Issue by dlgur1994** [wikibook/ml-definitive-guide#2]
In[5]:
irisDF['target'] = iris.target
iris_result = irisDF.groupby(['target','cluster'])['sepal_length'].count()
print(iris_result)

에서 다음으로 변경 필요

irisDF['target'] = iris.target
**irisDF['cluster'] = kmeans.labels_**
iris_result = irisDF.groupby(['target','cluster'])['sepal_length'].count()
print(iris_result)

**Comment by wikibook** [comment]
안녕하세요. 위키북스 담당자입니다.
불편을 드려 죄송합니다.
말씀해 주신 내용을 저자분께 전달했고, 말씀하신 대로 해당 코드 내용을 수정했습니다. 
또한 홈페이지 정오표에도 반영했으니 참고 부탁드립니다.

https://wikibook.co.kr/ml-definitive-guide/

좋은 의견 주셔서 감사합니다.
