### ISSUE TITLE
8.2 텍스트 사전 준비 작업(텍스트 전처리) 오류

### ISSUE THREAD

**Issue by dlgur1994** [wikibook/ml-definitive-guide#3]
In [4]
from nltk import sent_tokenize

#다음 추가 필요
**import nltk
nltk.download('punkt')**

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
               You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(type(sentences),len(sentences))
print(sentences)

**Comment by wikibook** [comment]
안녕하세요. 위키북스 담당자입니다.
불편을 드려 죄송합니다.
이 부분도 마찬가지로 저자분께 전달했고, 말씀하신 대로 해당 코드 내용을 수정했습니다.
또한 홈페이지 정오표에도 반영했으니 참고 부탁드립니다.

https://wikibook.co.kr/ml-definitive-guide/

감사합니다!
