### ISSUE TITLE
8.2 텍스트 사전 준비 작업(텍스트 전처리) 오류 2

### ISSUE THREAD

**Issue by dlgur1994** [wikibook/ml-definitive-guide#4]
In [10]:
from nltk.stem import WordNetLemmatizer

**#다음 추가 필요
import nltk
nltk.download('wordnet')**

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

**Comment by wikibook** [comment]
안녕하세요. 위키북스 담당자입니다.
불편을 드려 죄송합니다.
말씀해 주신 내용을 저자분께 전달했고, 말씀하신 대로 해당 코드 내용을 수정했습니다.
또한 홈페이지 정오표에도 반영했으니 참고 부탁드립니다.

https://wikibook.co.kr/ml-definitive-guide/

좋은 의견 주셔서 감사합니다.
